### ISSUE TITLE
Cannot launch firefox with nvidia driver version 525, failed to initialise VAAPI connection

### ISSUE THREAD

**Issue by ImALoooserOk** [elFarto/nvidia-vaapi-driver#128] opened 2022-12-01 11:45 UTC
When i try and lauch firefox from console, i get this error:

```
[GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
ExceptionHandler::GenerateDump cloned child 24185
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```
This happened after i tried installing the driver, anyone know why?

**Comment by ArcticWolf-Biotech** [comment] 2022-12-01 15:51
what's your nvidia driver version, I'd to rollback to 520 from 525. Can't find why with the new version vaapi doesn't work

**Comment by ImALoooserOk** [comment] 2022-12-01 17:22
nvm works now, thanks

**Comment by CoelacanthusHex** [comment] 2022-12-01 17:44
Since the problem has not been fundamentally resolved, I think it is better to reopen this issue?

**Comment by ArcticWolf-Biotech** [comment] 2022-12-01 17:53
I mean, sure. This is just anything but a quickfix but i dont have the first idea why with the new version of nvidia drivers fails... maybe they changed something on cuda since they added support for the new graphics? I think I've read something on the drivers changelog

**Comment by elFarto** [comment] 2022-12-02 08:15
This issue is a duplicate of #126. The root issue is one of the CUDA-EGL interop methods we use is failing with the new driver. There doesn't appear to be any way around this, other than to use the direct-backend branch of this library, which is very experimental at the moment.

**Closed by elFarto** 2022-12-02 08:15 UTC
